Repository Itatech-Jr/Modern-School-Mobile, pull requests merged in 2022-12, with the labels that each got.

#2 Atualizar o readme
  README.md
Labels: documentation

#22 21 Criar Widget template do Drawer
  lib/app/feature/activity/widget/card_drawer_widget.dart
  lib/app/feature/activity/widget/drawer_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#24 23 Criar Widget do card de alunos
  lib/app/core/domain/entity/info_aluno_materia_entity.dart
  lib/app/feature/activity/widget/card_materia_widget.dart
  lib/app/share/card_style.dart
Labels: enhancement

#26 add: creating widget of search
  lib/app/feature/activity/widget/search_widget.dart
Labels: feature
